namespace: docker4laravel
resources:
  - applications/namespace.yml
  - applications/main-ingress.yml
  - applications/redis-01/pvc.yml
  - applications/redis-01/svc.yml
  - applications/redis-01/statefulset.yml
  - applications/laravel-app/svc.yml
  - applications/laravel-app/web.yml