apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: main-ingress
spec:
  rules:
    - host: development.websolutions.work
      http:
        paths:
          - backend:
              serviceName: web-svc
              servicePort: 80